### PR TITLE
Node portal atom

### PR DESCRIPTION
**Pull request by andyhorng**
Hi @djblue ,

As discussed in Slack. I try to implement the portal atom in node runtime without using promise. I tested in my local environment, it works well. I also changed the jvm runtime to get selected value without invoking rpc to client.

### CODE REVIEW

**Comment by djblue** [comment]
Hi @andyhorng, thanks for the PR! The overall approach seems reasonable and I would be happy to merge. It does looks like clj-kondo found an unused require:

```
src/portal/runtime/jvm/client.clj:60:8: warning: Unused private var portal.runtime.jvm.client/datafy
```

**Comment by djblue** [comment]
Looks like cljfmt found a whitespace formatting issue:

```
../src/portal/ui/state.cljs has incorrect formatting
--- a/home/runner/work/portal/src/portal/ui/state.cljs
+++ b/home/runner/work/portal/src/portal/ui/state.cljs
@@ -226,7 +226,7 @@
          :portal/next-state nil))))
 
 (defn- send-selected-value [_ _ state state']
-  (when (or (not (:selected state)) 
+  (when (or (not (:selected state))
             (not= (get-selected-value state)
                   (get-selected-value state')))
     (invoke 'portal.runtime/update-selected (get-selected-value state'))))
1 file(s) formatted incorrectly
```

Run `make fmt` to fix it 👌

**Comment by andyhorng** [comment]
Sorry for the trial and error. I can not run the unit test completely, it will be hanged in some test cases, I need time to figure it out. I will send the PR again after I fix it. Thanks.

**Comment by djblue** [comment]
I was able to merge these changes https://github.com/djblue/portal/commit/cc0c9ed8a564002fe797717f0c4acdde864d469b after I added https://github.com/djblue/portal/commit/9732a3d432a2d4b8a0b2ba61a0477a7d6d064704. Thanks again for all the hard work @andyhorng !

**Pull request closed without merging**
