### PR TITLE
Manage multiple project instances on IntelliJ extension

### PR DESCRIPTION
**Pull request by wilkerlucio**
Hello, I decide to try a take to fix the multi-project issues.

I notice the previous code was with the expectation of a single project getting managed, I switched that to a map managing multiple projects.

I just finished coding this, I think would be nice to try it better for a few days (although I could see the issues fixed on my initial tests here :)).

### CODE REVIEW

**Comment by wilkerlucio** [comment]
One thing that I would like to add here is to remove the project from `instances` once it's closed, but I'm not sure how to do that hooking.

**Comment by djblue** [comment]
@wilkerlucio I haven't had time to review this fix yet, but I should be able to soon. Thanks again for looking into this issue!

**Comment by djblue** [comment]
@wilkerlucio, this PR looks good to me! Has it worked in practice for you / do you think it's good to merge?

Also, if you want to fix formatting, you just do: `bb fmt`. I can also fix it on merge 👌

**Comment by wilkerlucio** [comment]
Just fixed format 👍 

And I've been using it since I sent the PR here, works fine for me under multiple projects.

The bug about the wrong styles still exists (I notice no change compared to the previous behavior, works fine on the first run, after the second it goes one bad, one good...)

**Pull request merged**
