### PR TITLE
Make values limit configurable

### PR DESCRIPTION
**Pull request by nenadalm**
Thanks for the awesome app.

I am trying to use Portal as ui for showing postgresql logs: https://github.com/nenadalm/postgresql-log-viewer#postgresql-log-viewer. Usually I want to see all queries formatted including parameters (they are separate to the sql query string in the log), so that I can just copy-paste the query I choose and run it (possibly because it is slow, incorrect, ...).

These queries are usually invoked during some http request.

Some apps I work with have way more than 25 quries per http request though, so it would be nice if I could somehow change this limit of 25 values.

This pr allows setting this limit to arbitrary value when opening portal.

### CODE REVIEW

**Comment by djblue** [comment]
Hi @nenadalm, thanks for the PR. The limit was set to prevent `tap>` spam which could cause issues with the ui. 

I think an alternative solution is to `tap>` the entire parsed log at once, something like:

```clojure
(->> (csv/read-csv *in*)
     log-parser/drop-invalid-lines
     (map (comp format-log log-parser/line->log))
     tap>)
```

Let me know what you think.

**Comment by nenadalm** [comment]
I don't think that's an option, or at least not as simple as the presented code, because it's not like the log viewer just parses log or part of it and that's it.

I feed the viewer with `tail -f /var/lib/pgsql/data/log/postgresql.csv`, where `-f ` is short for `--follow` and if new entry appears in the log, it is sent to the log viewer. So there would either have to be some debouncing and some logs would be sent in batches (which would be probably bad because they could have nonsensical grouping - as some queries might take longer, batch would be sent and then same request would then execute more queries which would be sent in different batch) or I would have to overwrite the portal atom with each received query, which I am not sure would be somehow helpful.

Other possibility would be to make the log file empty, wait until request finishes and then open log viewer, read the entire log and ignore entries that come later, after last line is read.

I am still not sure how exactly I wish to display queries from postgres or if Portal is good choice for that. For now I just open the viewer, wait for request to finish and then inspect queries. Then I either close the Portal or clear the values and run another request.

I might later do something like counting similar queries and what not (probably won't do, given history of my personal projects, but would be nice). So just reading entire log (or part of it) and ignoring more incoming queries would be ok possibly (I might still preserve current option though).

Maybe I should just close this pr then (or you can If you don't wish to have the limit configurable)?

**Comment by djblue** [comment]
@nenadalm, now that I understand your problem a little better, I think #18 might also solve your problem. Take a look and let me know.

**Comment by nenadalm** [comment]
Thanks, but it doesn't seem to work.

Using infinite lazy sequence would be probably possible, although when I tap the log or `(range)`, I see nothing in portal ui.

When I try to tap `(range 2000)` and I navigate to the sequence, I can immediately see that it has 2000 items in the right down corner, so I suppose portal doesn't work with infinite sequences (which the logs would be).

I am currently on portal 0.6.3 which seems to be newest.

Even if the sequences were working, I would probably appreciate some **follow** checkbox or something that would keep scrolling to the newest entries as they show up.

For now I'll just stick with workaround that overwrites portal's `limit-values` fn: https://github.com/nenadalm/postgresql-log-viewer/blob/38c08449328269f9bd67cf35e40ec157dc5a6e63/src/app/portal.clj#L8

**Comment by djblue** [comment]
@nenadalm  I just released `0.6.4` which will have the PR I mentioned above. Sorry for the confusion.

**Comment by nenadalm** [comment]
Thanks. I didn't realize it wasn't released.

The `(range)` works now, but the sequence with logs still doesn't appear.

When printing with `println` I can see it in console, but I can see nothing in ui. I guess that's becasue it blocks on reading next item (when I read less then 100 logs) because when I read more logs, I can see some logs show in the Portal.

**Pull request closed without merging**
